### PR TITLE
Fix a bug that Curl.urlalize will miss raw url's query params

### PR DESCRIPTION
**Pull request by twistfz**

### CODE REVIEW

**Comment by twistfz** [comment]
#328 Fix this bug

**Comment by Moeser** [comment]
@taf2 anything we need to do to get this merged?  This is a pretty big bug.

**Comment by robuye** [comment]
@taf2 could you release as `0.9.5` and push to rubygems please?

Thanks very much!

**Comment by taf2** [comment]
working on the release now.  I need to do better job maintaining this project... anyone want to help?

**Pull request merged**
