### PR TITLE
Documentation Tidy / Update

### PR DESCRIPTION
**Pull request by luke-hill**
I'm using this gem a lot. So figured I'd try and contribute to a bit of tidy-up before I look to contribute to anything else.

I've cleaned up the changelog, fixed some typos and amended some inconsistent formatting
I've done a bit of feng shui and some quick-win rubocop tidies, to try improve legibility
I've added a *very conservative* gem compatibility chart with the `libcurl` library. I've added in the SHA for the compatibility chart that this is a safety-first approach, so the versions in there will work, but others probably will too!

### CODE REVIEW

**Comment by luke-hill** [comment]
@robuye / @taf2 - Does this PR seem appropriate / OK?

**Comment by taf2** [comment]
Will try to review today - thanks!

**Comment by taf2** [comment]
Looks good, will merge into nice I’m back to a real keyboard later this morning

**Comment by luke-hill** [comment]
Thoughts @taf2 / @robuye ?

**Comment by robuye** [comment]
Hey @luke-hill sorry for the long wait. I think your updates are good & make `curb` look better :+1:

**Comment by taf2** [comment]
Okay thank you for this update.  Merged your changes after resolving conflict

**Pull request closed without merging**
