### PR TITLE
Add cookielist method to Curb::Easy

### PR DESCRIPTION
**Pull request by Korrigan**
Hi there !

I just implemented a cookielist method on Curb::Easy for my personal needs, let me know if this looks good to you. It deals with https://curl.haxx.se/libcurl/c/CURLINFO_COOKIELIST.html

Also, thank you for writing this gem in the first place, that's incredibly useful to me!

### CODE REVIEW

**Comment by Korrigan** [comment]
By the way, it fixes #11

**Comment by taf2** [comment]
@Korrigan thank you this is awesome!   I want to merge this in but was wondering if you might mind adding a test case for this new feature first in tests/tc_curl_easy.rb and also ensure that any feature libcurl features introduced are checked for compatibility in ext/extconf.rb

**Comment by Korrigan** [comment]
Hi @taf2 

The check for libcurl support of CURLINFO_COOKIELIST option was already added to ext/exctonf.rb in f22ca57e24636f5f3ceff57b920a99b8f2a27ad5, so I guess I have nothing to do about this, right?

I'll try to write a test case during the weekend, I'm not yet sure of the best way to test this but I'll figure it out.

**Comment by taf2** [comment]
Thanks @Korrigan !

**Comment by Korrigan** [comment]
Hey @taf2, does this looks good to you ?

**Comment by taf2** [comment]
Looks great! Thank you.

**Pull request merged**
